[package]
name = "main_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
sub_lib = { workspace = true }

[dev-dependencies]
cucumber = { workspace = true }
tokio = { workspace = true }

[[test]]
name = "uat"
harness = false
